version: "2"
services:
  server:
    image: klakegg/hugo:0.88.0-ext-alpine
    command: ["server", "-s", "/src", "-D", "--bind", "0.0.0.0", "--ignoreCache"]
    volumes:
      - .:/src
    ports:
      - "1313:1313"
  spellchecker:
    image: tmaier/markdown-spellcheck:latest
    command: "--en-us --ignore-numbers --ignore-acronyms --report \"content/**/*.md\""
    volumes:
      - .:/workdir
  linkchecker:
    image: chabad360/htmlproofer:latest
    command: 'htmlproofer ./public --allow-hash-href --disable-external --check-html --checks-to-ignore ScriptCheck --empty-alt-ignore --file-ignore /.*apidocs.*/,/.*\/zh.*/,/.*\/es.*/,/.*\/docs\/reference\/api.*/,/.*\/docs\/reference\/config.*/,/.*\/community\/events.*/'
    volumes:
      - ./public:/public